# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_campaign_scheduled_plan_timeline:
    pattern:  /campaign/scheduled/plan/timeline
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:Plan:timeline }

campaignchain_campaign_scheduled_plan_timeline_fullscreen:
    pattern:  /campaign/scheduled/plan/timeline/fullscreen
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:Plan:timelineFullScreen }

campaignchain_campaign_scheduled_plan_timeline_detail:
    pattern:  /campaign/scheduled/plan/timeline/{id}
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:Plan:timelineDetail }

campaignchain_campaign_scheduled_plan_timeline_detail_fullscreen:
    pattern:  /campaign/scheduled/plan/timeline/fullscreen/{id}
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:Plan:timelineDetailFullScreen }

campaignchain_campaign_scheduled_plan_calendar:
    pattern:  /campaign/scheduled/plan/calendar
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:Plan:calendar }

campaignchain_campaign_scheduled_new:
    pattern:  /campaign/scheduled/new
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:new }

campaignchain_campaign_scheduled_edit:
    pattern:  /campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:edit }

campaignchain_campaign_scheduled_edit_modal:
    pattern:  /modal/campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:editModal }

campaignchain_campaign_scheduled_edit_api:
    pattern:  /api/private/campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:editApi }
    options:
        expose: true

campaignchain_campaign_scheduled_copy:
    pattern:  /campaign/scheduled/copy/{id}
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:copy }