# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_campaign_scheduled_new:
    pattern:  /campaign/scheduled/new
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:new }

campaignchain_campaign_scheduled_edit:
    pattern:  /campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:edit }

campaignchain_campaign_scheduled_edit_modal:
    pattern:  /modal/campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:editModal }

campaignchain_campaign_scheduled_edit_api:
    pattern:  /api/v1/campaign/scheduled/{id}/edit
    defaults: { _controller: CampaignChainCampaignScheduledCampaignBundle:ScheduledCampaign:editApi }
    options:
        expose: true