# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.campaign.scheduled.copy:
        class: CampaignChain\Campaign\ScheduledCampaignBundle\EntityService\CopyService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]